sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
        endpoint: oss-cn-beijing.aliyuncs.com
        access-key-id: LTAI5tMPeZMQMuJEM5TLxeXj
        access-key-secret: 6MAG4X9zD0VvJDGnR6z9sxvySi5to7
        bucket-name: sky-take-out-qtt
